[proxmox_vms]
kubernetes ansible_host=127.0.0.1 ansible_user=bababa
worker-rhel ansible_host=127.0.0.1 ansible_user=bababa
worker-ubuntu ansible_host=127.0.0.1 ansible_user=bababa
nfs-server ansible_host=127.0.0.1 ansible_user=bababa
TrueNAS ansible_host=127.0.0.1 ansible_user=bababa

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
