[proxmox_vms]
kubernetes ansible_host=172.31.0.9
kubernetes ansible_host=192.168.0.88
worker-rhel ansible_host=172.32.0.5
worker-rhel ansible_host=192.168.0.192
worker-ubuntu ansible_host=172.32.0.6
worker-ubuntu ansible_host=192.168.0.134
nfs-server ansible_host=172.31.0.11
TrueNAS ansible_host=172.31.0.5
TrueNAS ansible_host=172.16.1.1
TrueNAS ansible_host=172.16.0.1
test-server ansible_host=172.31.0.13

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'