[proxmox_vms]
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
kubernetes ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
worker-rhel ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
worker-ubuntu ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
test-server ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
Ubuntu24.04-template ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
nfs-server ansible_host=pending ansible_user=bababa
# try関数を使って、IPが取れない場合は一時的に "pending" と表示させる
TrueNAS ansible_host=pending ansible_user=bababa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'