apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-setup-job
  namespace: flux-system
  labels:
    build-id: placeholder
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: ansible-sa
      initContainers:
      - name: set-perms
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /home/ansible/.ansible && chown -R 1500:1500 /home/ansible/.ansible && \
            cp /secrets/private_key /ssh/private_key && \
            chown 1500:1500 /ssh/private_key && \
            chmod 400 /ssh/private_key
        volumeMounts:
        - name: home-dir
          mountPath: /home/ansible
        - name: ssh-key
          mountPath: /secrets
          readOnly: true
        - name: ssh-dir
          mountPath: /ssh

      - name: git-sync
        image: alpine/git
        command: ["git", "clone", "https://github.com/MoyashiWithDevice/ansible-resources.git", "/ansible"]
        volumeMounts:
        - name: playbook-storage
          mountPath: /ansible

      containers:
      - name: ansible
        image: bababa2547/ansible-ssh:latest
        env:
        - name: HOME
          value: /home/ansible
        - name: ANSIBLE_LOCAL_TEMP
          value: "/tmp/ansible"
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        volumeMounts:
        - name: ansible-tmp
          mountPath: /home/ansible/.ansible
        - name: ssh-dir
          mountPath: /home/ansible/.ssh
        - name: playbook-storage
          mountPath: /ansible
        workingDir: /ansible
        command: ["ansible-playbook", "-i", "inventory.ini", "main.yaml", "--private-key", "/home/ansible/.ssh/private_key"]
        #command: ["sleep", "3600"]

      volumes:
      - name: ssh-key
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ansible-vault-spc"
      - name: ssh-dir
        emptyDir: {}
      - name: playbook-storage
        emptyDir: {}
      - name: ansible-tmp
        emptyDir: {}
      - name: home-dir
        emptyDir: {}
      restartPolicy: Never
