# - hosts: [kubernetes, worker-rhel, worker-ubuntu, nfs-server, test-server]
- hosts: [kube-ctrl-2]
  become: true
  tasks:
    # メモリキャッシュを破棄するタスク
    - name: sync data to disk before dropping caches
      command: sync

    - name: clear memory cache (PageCache, dentries, and inodes)
      shell: echo 3 > /proc/sys/vm/drop_caches
      