name: Update Ansible Patch

on:
  push:
    branches: [main]
    paths:
      - main.yaml

jobs:
  update-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Patch
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H-%M')
          echo "apiVersion: batch/v1" > jobs/patch.yaml
          echo "kind: Job" >> jobs/patch.yaml
          echo "metadata:" >> jobs/patch.yaml
          echo "  name: ansible-setup-job" >> jobs/patch.yaml
          echo "  namespace: flux-system" >> jobs/patch.yaml
          echo "  labels:" >> jobs/patch.yaml
          echo "    build-id: \"$TIMESTAMP\"" >> jobs/patch.yaml

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD
